# Generated by Django 3.0.7 on 2021-05-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0010_auto_20210518_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
    ]
