# Generated by Django 3.0.7 on 2021-05-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0014_auto_20210518_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='category',
            new_name='categorys',
        ),
    ]
