# Generated by Django 3.0.7 on 2021-05-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0016_auto_20210518_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
