# Generated by Django 3.0.7 on 2021-05-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0017_quizcategory_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
