# Generated by Django 3.0.7 on 2021-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0020_auto_20210615_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='related_topics',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
